version: "3"

services:
  kivy:
    build:
      context: .
      dockerfile: Dockerfile
    image: kivy
    ports:
      - "8000:8000"
    volumes:
      - ./:/home/kivy/app
    working_dir: /home/kivy/app
